apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-dpl
  labels:
    app: jenkins-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        # volumeMounts:
        # - name: jenkins-vol
        #   mountPath: /var/jenkins_home
        # securityContext:
        #   allowPrivilegeEscalation: true
        ports:
        # - name: http
        - containerPort: 8080
        # # - name: ssh
        # - containerPort: 22
      # volumes:
      # - name: jenkins-vol
      #   hostPath:
      #     # directory location on host
      #     path: /var/jenkins_home
      #     # this field is optional
      #     type: DirectoryOrCreate
