apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-dpl
  labels:
    app: jenkins-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        volumeMounts:
        - name: jenkins-vol
          mountPath: /var/jenkins_home
        ports:
        - name: http
        containerPort: 8080
        - name: ssh
        containerPort: 22
        


apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
  volumes:
  - name: redis-storage
    emptyDir: {}



jenkins:
    image: jenkins/jenkins:lts
    hostname: jenkins.example.com
    ports:
      - "50000:8080"
      - "50022:22"
    volumes:
      - "$PWD/jenkins:/var/jenkins_home"
    restart: always