kind: Service
apiVersion: v1
metadata:
  name: jenkins-svc
spec:
  selector:
    app: jenkins-app
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30050
